export const FETCH_BUILDS = 'FETCH_BUILDS'
export const FETCH_BUILDS_SUCCESS = 'FETCH_BUILDS_SUCCESS'
export const FETCH_BUILDS_FAILURE = 'FETCH_BUILDS_FAILURE'

export const FETCH_BUILD_DETAILS = 'FETCH_BUILD_DETAILS'
export const FETCH_BUILD_DETAILS_SUCCESS = 'FETCH_BUILD_DETAILS_SUCCESS'
export const FETCH_BUILD_DETAILS_FAILURE = 'FETCH_BUILD_DETAILS_FAILURE'

export const POST_BUILD = 'POST_BUILD'
export const POST_BUILD_SUCCESS = 'POST_BUILD_SUCCESS'
export const POST_BUILD_FAILURE = 'POST_BUILD_FAILURE'
