export const FETCH_BUILDS = 'FETCH_BUILDS'
export const FETCH_BUILDS_SUCCESS = 'FETCH_BUILDS_SUCCESS'
export const FETCH_BUILDS_FAILURE = 'FETCH_BUILDS_FAILURE'

export const FETCH_BUILD_DETAILS = 'FETCH_BUILD_DETAILS'
export const FETCH_BUILD_DETAILS_SUCCESS = 'FETCH_BUILD_DETAILS_SUCCESS'
export const FETCH_BUILD_DETAILS_FAILURE = 'FETCH_BUILD_DETAILS_FAILURE'

export const POST_BUILD = 'POST_BUILD'
export const POST_BUILD_SUCCESS = 'POST_BUILD_SUCCESS'
export const POST_BUILD_FAILURE = 'POST_BUILD_FAILURE'
export const POST_BUILD_CLEAR = 'POST_BUILD_CLEAR'

export const EDIT_BUILD = 'EDIT_BUILD'
export const EDIT_BUILD_SUCCESS = 'EDIT_BUILD_SUCCESS'
export const EDIT_BUILD_FAILURE = 'EDIT_BUILD_FAILURE'
export const EDIT_BUILD_CLEAR = 'EDIT_BUILD_CLEAR'

export const NEW_BUILD_LEVEL = 'NEW_BUILD_LEVEL'
export const NEW_BUILD_LEVEL_SUCCESS = 'NEW_BUILD_LEVEL_SUCCESS'
export const NEW_BUILD_LEVEL_FAILURE = 'NEW_BUILD_LEVEL_FAILURE'
export const NEW_BUILD_LEVEL_CLEAR = 'NEW_BUILD_LEVEL_CLEAR'

export const EDIT_BUILD_LEVEL = 'EDIT_BUILD_LEVEL'
export const EDIT_BUILD_LEVEL_SUCCESS = 'EDIT_BUILD_LEVEL_SUCCESS'
export const EDIT_BUILD_LEVEL_FAILURE = 'EDIT_BUILD_LEVEL_FAILURE'
export const EDIT_BUILD_LEVEL_CLEAR = 'EDIT_BUILD_LEVEL_CLEAR'

export const DELETE_BUILD = 'DELETE_BUILD'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const DELETE_FAILURE = 'DELETE_FAILURE'
export const DELETE_CLEAR = 'DELETE_CLEAR'

export const STORE_CURRENT_LEVEL = 'STORE_CURRENT_LEVEL'
